from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel
from adaptive_questions import generate_followup_questions

router = APIRouter()


class FollowupRequest(BaseModel):
    symptoms: str


class FollowupResponse(BaseModel):
    questions: list


@router.post("/questions", response_model=FollowupResponse)
async def get_followup_questions(request: Request, body: FollowupRequest):
    """
    Takes initial symptoms and returns 3 follow-up questions
    generated by the LLM via adaptive_questions.py
    """
    symptoms = body.symptoms.strip()
    if not symptoms:
        raise HTTPException(status_code=400, detail="Symptoms cannot be empty.")

    try:
        questions = generate_followup_questions(symptoms)
        return FollowupResponse(questions=questions)
    except Exception as e:
        # Fallback questions if LLM fails
        return FollowupResponse(questions=[
            "How long have you had these symptoms?",
            "Are the symptoms getting worse?",
            "Do you have any fever or pain?"
        ])